# Creating the secret before referencing it in the deployment

apiVersion: v1
kind: Secret
metadata:
    name: mongo-secret
type: Opaque
data:
    # Should use a more completed username and password
    # echo -n 'username' | base64
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=